name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card (dark mode)
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: >-
            {
              "username": "${{ github.repository_owner }}",
              "show_icons": true,
              "include_all_commits": true,
              "exclude_repo": "github-readme-stats",
              "role": "OWNER,COLLABORATOR",
              "line_height": 25,
              "card_width": 420,
              "theme": "bear",
              "hide_border": true,
              "show": "reviews,discussions_started,discussions_answered",
              "rank_icon": "percentile"
            }
          path: profile/stats-dark-mode.svg
          token: ${{ secrets.README_STATS_TOKEN }}

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: >-
            {
              "username": "${{ github.repository_owner }}",
              "show_icons": true,
              "include_all_commits": true,
              "exclude_repo": "github-readme-stats",
              "role": "OWNER,COLLABORATOR",
              "line_height": 25,
              "card_width": 420,
              "theme": "default",
              "hide_border": true,
              "show": "reviews,discussions_started,discussions_answered",
              "rank_icon": "percentile"
            }
          path: profile/stats.svg
          token: ${{ secrets.README_STATS_TOKEN }}

      - name: Generate top languages card (dark mode)
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: >-
            {
              "username": "${{ github.repository_owner }}",
              "count_private": true,
              "langs_count": 12,
              "role": "OWNER,COLLABORATOR",
              "layout": "compact",
              "size_weight": 0.4,
              "count_weight": 0.6,
              "hide_border": true,
              "theme": "bear"
            }
          path: profile/top-langs-dark-mode.svg
          token: ${{ secrets.README_STATS_TOKEN }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: >-
            {
              "username": "${{ github.repository_owner }}",
              "count_private": true,
              "langs_count": 12,
              "role": "OWNER,COLLABORATOR",
              "layout": "compact",
              "size_weight": 0.4,
              "count_weight": 0.6,
              "hide_border": true,
              "theme": "default"
            }
          path: profile/top-langs.svg
          token: ${{ secrets.README_STATS_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
